class AlertModalAction {
  static PREVENT_MODAL = "PREVENT_MODAL";
  static PREPARE_UNSAVED_MODAL = "PREPARE_UNSAVED_MODAL";
  static REQUIRE_CONFIRMATION_MODAL = "REQUIRE_CONFIRMATION_MODAL";
  static CUSTOM_CONFIRMATION_MODAL = "CUSTOM_CONFIRMATION_MODAL";
}

export default AlertModalAction;
